package pl.elpassion.iot.alien

import java.util.*


data class Quote(val sentence: String, val author: String)

val FUNNY_QUOTES = listOf(
        Quote("Always remember that you are absolutely unique. Just like everyone else.", "Margaret Mead"),
        Quote("People who think they know everything are a great annoyance to those of us who do.", "Isaac Asimov"),
        Quote("Get your facts first, then you can distort them as you please.", "Mark Twain"),
        Quote("A woman\'s mind is cleaner than a man\'s: She changes it more often.", "Oliver Herford"),
        Quote("A day without sunshine is like, you know, night.", "Steve Martin"),
        Quote("I may be drunk, Miss, but in the morning I will be sober and you will still be ugly.", "Winston Churchill"),
        Quote("A successful man is one who makes more money than his wife can spend. A successful woman is one who can find such a man.", "Lana Turner"),
        Quote("Weather forecast for tonight: dark.", "George Carlin"),
        Quote("Roses are red, violets are blue, I\'m schizophrenic, and so am I.", "Oscar Levant"),
        Quote("My fake plants died because I did not pretend to water them.", "Mitch Hedberg"),
        Quote("It takes considerable knowledge just to realize the extent of your own ignorance.", "Thomas Sowell"),
        Quote("The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.", "Terry Pratchett"),
        Quote("All generalizations are false, including this one.", "Mark Twain"),
        Quote("Prejudice is a great time saver. You can form opinions without having to get the facts.", "E. B. White"),
        Quote("They say marriages are made in Heaven. But so is thunder and lightning.", "Clint Eastwood"),
        Quote("No man has a good enough memory to be a successful liar.", "Abraham Lincoln"),
        Quote("I always wanted to be somebody, but now I realize I should have been more specific.", "Lily Tomlin"),
        Quote("Before I refuse to take your questions, I have an opening statement.", "Ronald Reagan"),
        Quote("The chief function of the body is to carry the brain around.", "Thomas A. Edison"),
        Quote("Do not worry about avoiding temptation. As you grow older it will avoid you.", "Joey Adams"),
        Quote("Life is hard. After all, it kills you.", "Katharine Hepburn"),
        Quote("Everything I like is either illegal, immoral or fattening.", "Alexander Woollcott"),
        Quote("Society is like a stew. If you don\'t stir it up every once in a while then a layer of scum floats to the top.", "Edward Abbey"),
        Quote("I cook with wine, sometimes I even add it to the food.", "W. C. Fields"),
        Quote("Common sense is the collection of prejudices acquired by age eighteen.", "Albert Einstein"),
        Quote("I like long walks, especially when they are taken by people who annoy me.", "Fred Allen"),
        Quote("We owe a lot to Thomas Edison - if it wasn\'t for him, we\'d be watching television by candlelight.", "Milton Berle"),
        Quote("Never put a sock in a toaster.", "Eddie Izzard"),
        Quote("I would like to die on Mars. Just not on impact.", "Elon Musk"),
        Quote("I have a memory like an elephant. I remember every elephant I\'ve ever met.", "Herb Caen"),
        Quote("TV is chewing gum for the eyes.", "Frank Lloyd Wright"),
        Quote("I can speak Esperanto like a native.", "Spike Milligan"),
        Quote("I hate housework! You make the beds, you do the dishes and six months later you have to start all over again.", "Joan Rivers"),
        Quote("When I was a boy the Dead Sea was only sick.", "George Burns"),
        Quote("A sure cure for seasickness is to sit under a tree.", "Spike Milligan"),
        Quote("I am certain there is too much certainty in the world.", "Michael Crichton"),
        Quote("It\'s always funny until someone gets hurt. Then it\'s just hilarious.", "Bill Hicks"),
        Quote("Some people say funny things, but I say things funny.", "Don Rickles"),
        Quote("When I die, I want to go peacefully like my grandfather did–in his sleep. Not yelling and screaming like the passengers in his car.", "Bob Monkhouse"),
        Quote("First the doctor told me the good news: I was going to have a disease named after me.", "Steve Martin"),
        Quote("Dogs have masters. Cats have staff.", ""),
        Quote("Why do people say \"no offense\" right before they\'re about to offend you?", ""),
        Quote("By all means, marry. If you get a good wife, you\'ll become happy; if you get a bad one, you\'ll become a philosopher.", "Socrates"),
        Quote("The only mystery in life is why the kamikaze pilots wore helmets.", "Al Mcguire"),
        Quote("Patience is something you admire in the driver behind you, but not in one ahead.", "Bill Mcglashen"),
        Quote("Women who seek to be equal with men lack ambition.", "Marilyn Monroe"),
        Quote("I read recipes the same way I read science fiction. I get to the end and I think: Well, that\'s not going to happen.", ""),
        Quote("Instead of getting married again, I\'m going to find a woman I don\'t like and just give her a house.", "Rod Stewart"),
        Quote("The human brain is a wonderful thing. It starts working the moment you are born, and never stops until you stand up to speak in public.", "George Jessel"),
        Quote("I\'ve had bad luck with both my wives. The first one left me and the second one didn\'t.", "Patrick Murray"),
        Quote("I have to exercise early in the morning before my brain figures out what I\'m doing.", "")
)

val SMART_QUOTES = listOf(
        Quote("Life is about making an impact, not making an income.", "Kevin Kruse"),
        Quote("Whatever the mind of man can conceive and believe, it can achieve.", "Napoleon Hill"),
        Quote("Strive not to be a success, but rather to be of value.", "Albert Einstein"),
        Quote("You miss 100% of the shots you don\'t take.", "Wayne Gretzky"),
        Quote("Life is what happens to you while you\'re busy making other plans.", "John Lennon"),
        Quote("We become what we think about.", "Earl Nightingale"),
        Quote("Life is 10% what happens to me and 90% of how I react to it.", "Charles Swindoll"),
        Quote("The mind is everything. What you think you become.", "Buddha"),
        Quote("The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"),
        Quote("An unexamined life is not worth living.", "Socrates"),
        Quote("Your time is limited, so don\'t waste it living someone else\'s life.", "Steve Jobs"),
        Quote("I am not a product of my circumstances. I am a product of my decisions.", "Stephen Covey"),
        Quote("Every child is an artist.  The problem is how to remain an artist once he grows up.", "Pablo Picasso"),
        Quote("You can never cross the ocean until you have the courage to lose sight of the shore.", "Christopher Columbus"),
        Quote("I\'ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", "Maya Angelou"),
        Quote("Whether you think you can or you think you can\'t, you\'re right.", "Henry Ford"),
        Quote("The best revenge is massive success.", "Frank Sinatra"),
        Quote("People often say that motivation doesn\'t last. Well, neither does bathing.  That\'s why we recommend it daily.", "Zig Ziglar"),
        Quote("Life shrinks or expands in proportion to one\'s courage.", "Anais Nin"),
        Quote("If you hear a voice within you say \"you cannot paint,\" then by all means paint and that voice will be silenced.", "Vincent Van Gogh"),
        Quote("There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "Aristotle"),
        Quote("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"),
        Quote("Everything you\'ve ever wanted is on the other side of fear.", "George Addair"),
        Quote("We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", "Plato"),
        Quote("Too many of us are not living our dreams because we are living our fears.", "Les Brown"),
        Quote("If you want to lift yourself up, lift up someone else.", "Booker T. Washington"),
        Quote("In order to succeed, your desire for success should be greater than your fear of failure.", "Bill Cosby"),
        Quote("Build your own dreams, or someone else will hire you to build theirs.", "Farrah Gray"),
        Quote("Education costs money.  But then so does ignorance.", "Sir Claus Moser"),
        Quote("Remember that not getting what you want is sometimes a wonderful stroke of luck.", "Dalai Lama"),
        Quote("You can\'t use up creativity.  The more you use, the more you have.", "Maya Angelou"),
        Quote("The only way to do great work is to love what you do.", "Steve Jobs"),
        Quote("The question isn\'t who is going to let me; it\'s who is going to stop me.", "Ayn Rand"),
        Quote("Dreaming, after all, is a form of planning.", "Gloria Steinem"),
        Quote("It\'s not what you look at that matters, it\'s what you see.", "Henry David Thoreau"),
        Quote("A day of worry is more exhausting than a week of work.", "John Lubbock"),
        Quote("Beware of false knowledge; it is more dangerous than ignorance.", "George Bernard Shaw"),
        Quote("The opinion which other people have of you is their problem, not yours.", "Elisabeth Kubler-Ross"),
        Quote("Whatever you do in life, surround yourself with smart people who\'ll argue with you.", "John Wooden"),
        Quote("Knowledge is of no value unless you put it into practice.", "Anton Chekhov"),
        Quote("Intelligence is the ability to adapt to change.", "Stephen Hawking"),
        Quote("People won\'t have time for you if you are always angry or complaining.", "Stephen Hawking"),
        Quote("However difficult life may seem, there is always something you can do and succeed at.", "Stephen Hawking"),
        Quote("We are all now connected by the Internet, like neurons in a giant brain.", "Stephen Hawking"),
        Quote("I believe alien life is quite common in the universe, although intelligent life is less so. Some say it has yet to appear on planet Earth.", "Stephen Hawking"),
        Quote("Science is not only a disciple of reason but, also, one of romance and passion.", "Stephen Hawking"),
        Quote("We love life, not because we are used to living but because we are used to loving.", "Friedrich Nietzsche"),
        Quote("Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you.", "Friedrich Nietzsche"),
        Quote("Without music, life would be a mistake.", "Friedrich Nietzsche"),
        Quote("All things are subject to interpretation whichever interpretation prevails at a given time is a function of power and not truth.", "Friedrich Nietzsche"),
        Quote("He who has a why to live can bear almost any how.", "Friedrich Nietzsche"),
        Quote("In individuals, insanity is rare; but in groups, parties, nations and epochs, it is the rule.", "Friedrich Nietzsche"),
        Quote("Thoughts are the shadows of our feelings - always darker, emptier and simpler.", "Friedrich Nietzsche"),
        Quote("There is always some madness in love. But there is also always some reason in madness.", "Friedrich Nietzsche"),
        Quote("A casual stroll through the lunatic asylum shows that faith does not prove anything.", "Friedrich Nietzsche"),
        Quote("The true man wants two things: danger and play. For that reason he wants woman, as the most dangerous plaything.", "Friedrich Nietzsche"),
        Quote("It is not a lack of love, but a lack of friendship that makes unhappy marriages.", "Friedrich Nietzsche"),
        Quote("The most common lie is that which one lies to himself; lying to others is relatively an exception.", "Friedrich Nietzsche"),
        Quote("We should consider every day lost on which we have not danced at least once. And we should call every truth false which was not accompanied by at least one laugh.", "Friedrich Nietzsche"),
        Quote("It is not when truth is dirty, but when it is shallow, that the lover of knowledge is reluctant to step into its waters.", "Friedrich Nietzsche"),
        Quote("There is more wisdom in your body than in your deepest philosophy.", "Friedrich Nietzsche"),
        Quote("In heaven, all the interesting people are missing.", "Friedrich Nietzsche"),
        Quote("Fear is the mother of morality.", "Friedrich Nietzsche"),
        Quote("Whatever is done for love always occurs beyond good and evil.", "Friedrich Nietzsche"),
        Quote("Those who cannot understand how to put their thoughts on ice should not enter into the heat of debate.", "Friedrich Nietzsche")
)

private val RANDOM = Random()

fun <T> List<T>.random() = this[RANDOM.nextInt(size)]
